In [288]:
import pandas as pd
import numpy as np

In [289]:
df=pd.read_excel('data.xlsx')
df.head()

            Timestamp  ...                                       URL-honeypot
0 2020-08-19 20:00:33  ...                                                NaN
1 2020-08-24 14:18:50  ...                                http://krdsprt.club
2 2020-08-25 10:12:34  ...                                 http://topgrf.club
3 2020-08-25 14:07:49  ...  https://www.monkeydigital.co/Get-Guaranteed-Do...
4 2020-08-25 19:05:13  ...                           http://krdsprt.club/base

[5 rows x 10 columns]

In [290]:
#cleaning data
#creating new column for isBot or not
df['isBot']=df['URL-honeypot'].notna().astype(int)
df.head()

            Timestamp  ... isBot
0 2020-08-19 20:00:33  ...     0
1 2020-08-24 14:18:50  ...     1
2 2020-08-25 10:12:34  ...     1
3 2020-08-25 14:07:49  ...     1
4 2020-08-25 19:05:13  ...     1

[5 rows x 11 columns]

In [291]:
df.isBot.value_counts()

isBot
0    4193
1    1573
Name: count, dtype: int64

In [292]:
df = df.drop(columns=['Full name'])
df

               Timestamp  ... isBot
0    2020-08-19 20:00:33  ...     0
1    2020-08-24 14:18:50  ...     1
2    2020-08-25 10:12:34  ...     1
3    2020-08-25 14:07:49  ...     1
4    2020-08-25 19:05:13  ...     1
...                  ...  ...   ...
5761                 NaT  ...     0
5762                 NaT  ...     0
5763                 NaT  ...     0
5764                 NaT  ...     0
5765                 NaT  ...     0

[5766 rows x 10 columns]

In [293]:
#handling missing values
df.fillna('', inplace=True)

               Timestamp  ... isBot
0    2020-08-19 20:00:33  ...     0
1    2020-08-24 14:18:50  ...     1
2    2020-08-25 10:12:34  ...     1
3    2020-08-25 14:07:49  ...     1
4    2020-08-25 19:05:13  ...     1
...                  ...  ...   ...
5761                 NaT  ...     0
5762                 NaT  ...     0
5763                 NaT  ...     0
5764                 NaT  ...     0
5765                 NaT  ...     0

[5766 rows x 10 columns]

In [294]:
#Feature engineering
#raw data ke numbers e

In [295]:
#Text feature
from sklearn.feature_extraction.text import TfidfVectorizer
#TF-IDF use korbo
tfidf = TfidfVectorizer(max_features=500)
X_text = tfidf.fit_transform(df['Message'])

In [296]:
#checking the matrxi 
X_text.shape
x_normal_array= X_text.toarray()
print(x_normal_array)

[[0.        0.        0.        ... 0.        0.        0.1406087]
 [0.        0.        0.        ... 0.        0.        0.       ]
 [0.        0.        0.        ... 0.        0.        0.       ]
 ...
 [0.        0.        0.        ... 0.        0.        0.       ]
 [0.        0.        0.        ... 0.        0.        0.       ]
 [0.        0.        0.        ... 0.        0.        0.       ]]

In [297]:
#convertin into a dataframe
feature_name = tfidf.get_feature_names_out()
df_tfidf=pd.DataFrame(X_text.toarray(),columns=feature_name)
print(df_tfidf)

      000   01   0a   0d        10  ...  через       что  чтобы  шишки       это
0     0.0  0.0  0.0  0.0  0.000000  ...    0.0  0.138711    0.0    0.0  0.140609
1     0.0  0.0  0.0  0.0  0.000000  ...    0.0  0.000000    0.0    0.0  0.000000
2     0.0  0.0  0.0  0.0  0.000000  ...    0.0  0.000000    0.0    0.0  0.000000
3     0.0  0.0  0.0  0.0  0.000000  ...    0.0  0.000000    0.0    0.0  0.000000
4     0.0  0.0  0.0  0.0  0.000000  ...    0.0  0.000000    0.0    0.0  0.000000
...   ...  ...  ...  ...       ...  ...    ...       ...    ...    ...       ...
5761  0.0  0.0  0.0  0.0  0.112499  ...    0.0  0.000000    0.0    0.0  0.000000
5762  0.0  0.0  0.0  0.0  0.000000  ...    0.0  0.000000    0.0    0.0  0.000000
5763  0.0  0.0  0.0  0.0  0.000000  ...    0.0  0.000000    0.0    0.0  0.000000
5764  0.0  0.0  0.0  0.0  0.000000  ...    0.0  0.000000    0.0    0.0  0.000000
5765  0.0  0.0  0.0  0.0  0.000000  ...    0.0  0.000000    0.0    0.0  0.000000

[5766 rows x 500 columns]

In [298]:
#Email feature
df['Email_len']=df['Email'].apply(len)
df['has_numbers_email']=df['Email'].str.contains(r'\d').astype(int)
df['is_free_domain'] = df['Email'].str.contains('gmail|yahoo|hotmail').astype(int)

In [299]:
#phone feature
df['Phone Number']  =df['Phone Number'].astype(str).apply(len)

In [300]:
#message behavior
df['msg_len'] =df['Message'].apply(len)
df['num_links'] =df['Message'].str.count('http')
df['num_special_chars']=df['Message'].str.count(r'[!@#$%^&*()]')

In [301]:
#time feature
df['Timestamp'] = pd.to_datetime(df['Timestamp'])
df['hour'] = df['Timestamp'].dt.hour
df['hour']

0       20.0
1       14.0
2       10.0
3       14.0
4       19.0
        ...
5761     NaN
5762     NaN
5763     NaN
5764     NaN
5765     NaN
Name: hour, Length: 5766, dtype: float64