In [910]:
import pandas as pd
import numpy as np

In [911]:
df=pd.read_excel('data.xlsx')
df.head()

            Timestamp  ...                                       URL-honeypot
0 2020-08-19 20:00:33  ...                                                NaN
1 2020-08-24 14:18:50  ...                                http://krdsprt.club
2 2020-08-25 10:12:34  ...                                 http://topgrf.club
3 2020-08-25 14:07:49  ...  https://www.monkeydigital.co/Get-Guaranteed-Do...
4 2020-08-25 19:05:13  ...                           http://krdsprt.club/base

[5 rows x 10 columns]

In [912]:
#cleaning data
#creating new column for isBot or not
df['isBot']=df['URL-honeypot'].notna().astype(int)
df.head()

            Timestamp  ... isBot
0 2020-08-19 20:00:33  ...     0
1 2020-08-24 14:18:50  ...     1
2 2020-08-25 10:12:34  ...     1
3 2020-08-25 14:07:49  ...     1
4 2020-08-25 19:05:13  ...     1

[5 rows x 11 columns]

In [913]:
df.isBot.value_counts()

isBot
0    4193
1    1573
Name: count, dtype: int64

In [914]:
df = df.drop(columns=['Full name'])
df

               Timestamp  ... isBot
0    2020-08-19 20:00:33  ...     0
1    2020-08-24 14:18:50  ...     1
2    2020-08-25 10:12:34  ...     1
3    2020-08-25 14:07:49  ...     1
4    2020-08-25 19:05:13  ...     1
...                  ...  ...   ...
5761                 NaT  ...     0
5762                 NaT  ...     0
5763                 NaT  ...     0
5764                 NaT  ...     0
5765                 NaT  ...     0

[5766 rows x 10 columns]

In [915]:
#handling missing values
df.fillna('', inplace=True)

               Timestamp  ... isBot
0    2020-08-19 20:00:33  ...     0
1    2020-08-24 14:18:50  ...     1
2    2020-08-25 10:12:34  ...     1
3    2020-08-25 14:07:49  ...     1
4    2020-08-25 19:05:13  ...     1
...                  ...  ...   ...
5761                 NaT  ...     0
5762                 NaT  ...     0
5763                 NaT  ...     0
5764                 NaT  ...     0
5765                 NaT  ...     0

[5766 rows x 10 columns]

In [916]:
#Feature engineering
#raw data ke numbers e

In [917]:
#Text feature
from sklearn.feature_extraction.text import TfidfVectorizer
#TF-IDF use korbo
tfidf = TfidfVectorizer(max_features=500)
X_text = tfidf.fit_transform(df['Message'])

In [918]:
#checking the matrxi
X_text.shape
x_normal_array= X_text.toarray()
print(x_normal_array)

[[0.        0.        0.        ... 0.        0.        0.1406087]
 [0.        0.        0.        ... 0.        0.        0.       ]
 [0.        0.        0.        ... 0.        0.        0.       ]
 ...
 [0.        0.        0.        ... 0.        0.        0.       ]
 [0.        0.        0.        ... 0.        0.        0.       ]
 [0.        0.        0.        ... 0.        0.        0.       ]]

In [919]:
#convertin into a dataframe
feature_name = tfidf.get_feature_names_out()
df_tfidf=pd.DataFrame(X_text.toarray(),columns=feature_name)
print(df_tfidf)

      000   01   0a   0d        10  ...  через       что  чтобы  шишки       это
0     0.0  0.0  0.0  0.0  0.000000  ...    0.0  0.138711    0.0    0.0  0.140609
1     0.0  0.0  0.0  0.0  0.000000  ...    0.0  0.000000    0.0    0.0  0.000000
2     0.0  0.0  0.0  0.0  0.000000  ...    0.0  0.000000    0.0    0.0  0.000000
3     0.0  0.0  0.0  0.0  0.000000  ...    0.0  0.000000    0.0    0.0  0.000000
4     0.0  0.0  0.0  0.0  0.000000  ...    0.0  0.000000    0.0    0.0  0.000000
...   ...  ...  ...  ...       ...  ...    ...       ...    ...    ...       ...
5761  0.0  0.0  0.0  0.0  0.112499  ...    0.0  0.000000    0.0    0.0  0.000000
5762  0.0  0.0  0.0  0.0  0.000000  ...    0.0  0.000000    0.0    0.0  0.000000
5763  0.0  0.0  0.0  0.0  0.000000  ...    0.0  0.000000    0.0    0.0  0.000000
5764  0.0  0.0  0.0  0.0  0.000000  ...    0.0  0.000000    0.0    0.0  0.000000
5765  0.0  0.0  0.0  0.0  0.000000  ...    0.0  0.000000    0.0    0.0  0.000000

[5766 rows x 500 columns]

In [920]:
#Email feature
df['Email_len']=df['Email'].apply(len)
df['has_numbers_email']=df['Email'].str.contains(r'\d').astype(int)
df['is_free_domain'] = df['Email'].str.contains('gmail|yahoo|hotmail').astype(int)

In [921]:
#phone feature
df['phone_len']  =df['Phone Number'].astype(str).apply(len)

In [922]:
#message behavior
df['msg_len'] =df['Message'].apply(len)
df['num_links'] =df['Message'].str.count('http')
df['num_special_chars']=df['Message'].str.count(r'[!@#$%^&*()]')

In [923]:
#time feature
df = df.drop(columns=['Timestamp', 'hour'], errors='ignore')
df.head()

  First name  Middle name    Last name  ... msg_len num_links num_special_chars
0  EdwardNex  EdwardNexFR  EdwardNexFR  ...    1043         2                 9
1   JimmySiG   JimmySiGAI   JimmySiGAI  ...     605         3                 1
2      Mike       Mike AX      Mike AX  ...     398         1                 2
3  DennisHob  DennisHobJQ  DennisHobJQ  ...     974         3                11
4  RobertDon  RobertDonGK  RobertDonGK  ...     957         1                 3

[5 rows x 16 columns]

In [924]:
#step 4 , we will combine features 
X_numeric =  df[['Email_len','has_numbers_email','is_free_domain','phone_len',
   'msg_len','num_links','num_special_chars']]

In [925]:
#Combine text + numeric features with scipy
from scipy.sparse import hstack
X = hstack([X_text,X_numeric])
y = df['isBot']

In [926]:
#error in model training because missing values in X(NaN)
#Random forest cant train on missing data

In [927]:
df.isna().sum()

First name           0
Middle name          0
Last name            0
Email                0
Phone Number         0
Subject              0
Message              0
URL-honeypot         0
isBot                0
Email_len            0
has_numbers_email    0
is_free_domain       0
phone_len            0
msg_len              0
num_links            0
num_special_chars    0
dtype: int64

In [928]:
np.isnan(X_numeric).sum()

Email_len            0
has_numbers_email    0
is_free_domain       0
phone_len            0
msg_len              0
num_links            0
num_special_chars    0
dtype: int64

In [929]:
X_numeric.dtypes

Email_len            int64
has_numbers_email    int64
is_free_domain       int64
phone_len            int64
msg_len              int64
num_links            int64
num_special_chars    int64
dtype: object

In [ ]:
#dataset final view
df.head()
df.to_csv("ml_dataset.csv",index=False)

  First name  Middle name    Last name  ... msg_len num_links num_special_chars
0  EdwardNex  EdwardNexFR  EdwardNexFR  ...    1043         2                 9
1   JimmySiG   JimmySiGAI   JimmySiGAI  ...     605         3                 1
2      Mike       Mike AX      Mike AX  ...     398         1                 2
3  DennisHob  DennisHobJQ  DennisHobJQ  ...     974         3                11
4  RobertDon  RobertDonGK  RobertDonGK  ...     957         1                 3

[5 rows x 16 columns]

In [931]:
#model training
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

X_train, X_test , y_train, y_test = train_test_split(X, y, test_size= 0.2)

model = RandomForestClassifier()
model.fit(X_train, y_train)

RandomForestClassifier()

In [932]:
#evaluate
from sklearn.metrics import classification_report

y_pred = model.predict(X_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.95      0.93      0.94       871
           1       0.81      0.86      0.83       283

    accuracy                           0.92      1154
   macro avg       0.88      0.90      0.89      1154
weighted avg       0.92      0.92      0.92      1154